name = "rkpr"
version = "0.1.0"
license = "MIT"
author = "Federico Benelli"
maintainer = "federico.benelli@mi.unc.edu.ar"
copyright = "Copyright 2022, Federico Benelli"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
#json-fortran.git = "https://github.com/jacobwilliams/json-fortran"
ftools.git = "https://github.com/fedebenelli/ftools"
test-drive.git = "https://github.com/fortran-lang/test-drive"
