name: Docs Generation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docs:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]
    
    # The type of runner that the job will run on
    runs-on: ${{ matrix.platform }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      
      - name: Install ford
        run: pip install ford
        
      - name: Install fpm
        run: bash tools/install_fpm.sh install
      
      - name: make docs
        run: ford docs.md

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update docs
        commit_options: '--no-verify --signoff'
        file_pattern: docs/*
        repository: .

        commit_user_name: DocsBot # defaults to "github-actions[bot]"
          #commit_user_email: my-github-actions-bot@example.org # defaults to "github-actions[bot]@users.noreply.github.com"
          #commit_author: DocsBot <actions@github.com> # defaults to author of the commit that triggered the run

        # Optional. Options used by `git-push`.
        # See https://git-scm.com/docs/git-push#_options
        push_options: '--force'
        
        # Optional. Disable dirty check and always try to create a commit and push
        skip_dirty_check: true    
        
        # Optional. Skip internal call to `git fetch`
        skip_fetch: true    
        
        # Optional. Skip internal call to `git checkout`
        skip_checkout: true

        # Optional. Prevents the shell from expanding filenames. 
        # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
        disable_globbing: true
