# This is a basic workflow to help you get started with Actions

name: Make unit tests

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]
    
    # The type of runner that the job will run on
    runs-on: ${{ matrix.platform }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      
      - name: Install gcovr
        run: pip install gcovr

      - name: Install fpm
        run: bash tools/install_fpm.sh install
      
      - name: fpm test
        run: bash tools/install_fpm.sh test

      - name: coverage
        run: gcovr --exclude "build/dependencies/.*"
